version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-prioridade-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: ${PORT:-3000}
      APP_BASE_URL: ${APP_BASE_URL:-http://localhost:3000}
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"

  postgres:
    image: postgres:16
    container_name: postgres-estoque
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
      - postgres_estoque_data:/var/lib/postgresql/data

volumes:
  postgres_estoque_data:
